
#Region "Copyright(c)"

'Copyright (c) 2006-2007 Hard Task Software Corporation. All rigths reserved.

#End Region

Public Structure DBTable

    'Define Constant For Each Table Name in Database

    Dim Virtual As String

#Region "Users And Permission"

    Public Const Form As String = "P_SystemForms"
    Public Const FormGroup As String = "P_SystemCategory"
    Public Const UserFormPermission As String = "P_SystemPermission"
    Public Const Users As String = "P_Users"
    Public Const UserLog As String = "_User_Log"

#End Region

#Region "PKTYPE"
    Public Const PK_Integer As Integer = 1
    Public Const PK_String As Integer = 2
#End Region
#Region "Files"

    Public Const CRDetails As String = "CRDetails"
    Public Const CustomerContacts As String = "CustomerContacts"
    Public Const CustomerData As String = "CustomerData"
    Public Const CustomerPayments As String = "CustomerPayments"
    Public Const CustomerReceivable As String = "CustomerReceivable"
    Public Const CustomerShipTo As String = "CustomerShipTo"
    Public Const D_ActionType As String = "D_ActionType"
    Public Const D_AccountType As String = "D_AccountType"
    Public Const D_CustomerAccountType As String = "D_CustomerAccountType"
    Public Const D_Area As String = "D_Area"
    Public Const D_BarcodeType As String = "D_BarcodeType"
    Public Const D_BlockType As String = "D_BlockType"
    Public Const D_Cashier As String = "D_Cashier"
    Public Const D_City As String = "D_City"
    Public Const D_CommissionType As String = "D_CommissionType"
    Public Const D_CompanyData As String = "D_CompanyData"
    Public Const D_CostCalculateMethod As String = "D_CostCalculateMethod"
    Public Const D_Country As String = "D_Country"
    Public Const D_Currency As String = "D_Currency"
    Public Const D_CustomerRank As String = "D_CustomerRank"
    Public Const D_CustomerType As String = "D_CustomerType"
    Public Const D_CustomerType1 As String = "D_CustomerType1"
    Public Const D_CustomerType2 As String = "D_CustomerType2"
    Public Const D_Dimention As String = "D_Dimention"
    Public Const D_DimentionAttribute As String = "D_DimentionAttribute"
    Public Const D_Discount As String = "D_Discount"
    Public Const D_DiscountListPrice As String = "D_DiscountListPrice"
    Public Const D_DiscountType As String = "D_DiscountType"
    Public Const D_DistributeExpensesMethod As String = "D_DistributeExpensesMethod"
    Public Const D_ExpensesType As String = "D_ExpensesType"
    Public Const D_ExRate As String = "D_ExRate"
    Public Const D_InventoryType As String = "D_InventoryType"
    'Public Const D_ItemClassType As String = "D_ItemClassType"
    Public Const D_ItemType As String = "D_ItemType"
    Public Const D_LocationType As String = "D_LocationType"
    Public Const D_MainCategory As String = "D_MainCategory"
    Public Const D_MainUnit As String = "D_MainUnit"
    Public Const D_PriceType As String = "D_PriceType"
    Public Const D_PricingMethod As String = "D_PricingMethod"
    Public Const D_PurchaseRequisitionStatus As String = "D_PurchaseRequisitionStatus"
    Public Const D_Reason As String = "D_Reason"
    Public Const D_RecallType As String = "D_RecallType"
    Public Const D_SalesRepresentative As String = "D_SalesRepresentative"
    Public Const D_ScheduleType As String = "D_ScheduleType"
    Public Const D_ShippingCompany As String = "D_ShippingCompany"
    Public Const D_ShippingMethod As String = "D_ShippingMethod"
    Public Const D_ShippingPrice As String = "D_ShippingPrice"
    Public Const D_Store As String = "D_Store"
    Public Const D_StoreLimitPurchase As String = "D_StoreLimitPurchase"
    Public Const D_SubCategory As String = "D_SubCategory"
    Public Const D_SubUnit As String = "D_SubUnit"
    Public Const D_SupplierContacts As String = "D_SupplierContacts"
    Public Const D_SupplierData As String = "D_SupplierData"
    Public Const D_SupplierType1 As String = "D_SupplierType1"
    Public Const D_SupplierType2 As String = "D_SupplierType2"
    Public Const D_Tax As String = "D_Tax"
    Public Const D_TenderDenominations As String = "D_TenderDenominations"
    Public Const D_TenderProperties As String = "D_TenderProperties"
    Public Const D_TenderType As String = "D_TenderType"
    Public Const D_WeekDays As String = "D_WeekDays"
    Public Const InventoryData As String = "InventoryData"
    Public Const InventoryEntry As String = "InventoryEntry"
    Public Const InventoryEntryDetails As String = "InventoryEntryDetails"
    Public Const InventoryOff As String = "InventoryOff"
    Public Const Item_Data As String = "Item_Data"
    Public Const Item_DiscountPriceList As String = "Item_DiscountPriceList"
    Public Const Item_Expire As String = "Item_Expire"
    Public Const Item_Kit As String = "Item_Kit"
    Public Const Item_Location As String = "Item_Location"
    Public Const Item_PriceList As String = "Item_PriceList"
    Public Const Item_Schedule As String = "Item_Schedule"
    Public Const Item_ScheduleTime As String = "Item_ScheduleTime"
    Public Const Item_Serial As String = "Item_Serial"
    Public Const Item_Substitutes As String = "Item_Substitutes"
    Public Const Item_Suppliers As String = "Item_Suppliers"
    'Public Const ItemClass As String = "ItemClass"
    'Public Const ItemClassComponent As String = "ItemClassComponent"
    Public Const PurchaseExpenses As String = "PurchaseExpenses"
    Public Const PurchaseOrder As String = "PurchaseOrder"
    Public Const PurchaseOrderDetails As String = "PurchaseOrderDetails"
    Public Const PurchaseOrderEntry As String = "PurchaseOrderEntry"
    Public Const PurchaseRequisition As String = "PurchaseRequisition"
    Public Const PurchaseRequisitionDetails As String = "PurchaseRequisitionDetails"
    Public Const Sales_Batch As String = "Sales_Batch"
    Public Const Sales_DropPayOut As String = "Sales_DropPayOut"
    Public Const Sales_OrderEntry As String = "Sales_OrderEntry"
    Public Const Sales_OrderHistory As String = "Sales_OrderHistory"
    Public Const Sales_Orders As String = "Sales_Orders"
    Public Const Sales_TaxEntry As String = "Sales_TaxEntry"
    Public Const Sales_TaxTotal As String = "Sales_TaxTotal"
    Public Const Sales_TenderEntry As String = "Sales_TenderEntry"
    Public Const Sales_TenderTotal As String = "Sales_TenderTotal"
    Public Const Sales_TrackShipping As String = "Sales_TrackShipping"
    Public Const Sales_Transaction As String = "Sales_Transaction"
    Public Const Sales_TransactionEntry As String = "Sales_TransactionEntry"
    Public Const Cheque As String = "Cheque"
    Public Const Quotation As String = "Quotation"
    Public Const Quotation_Entry As String = "Quotation_Entry"
#End Region


End Structure
