Public Module Table
    Public Account As String = "Account"
    Public Config As String = "Config"
    Public D_AccountType As String = "D_AccountType"
    Public D_BarcodeType As String = "D_BarcodeType"
    Public D_CostMethod As String = "D_CostMethod"
    Public D_Counter As String = "D_Counter"
    Public D_ItemCategory As String = "D_ItemCategory"
    Public D_ItemSubCategory As String = "D_ItemSubCategory"
    Public D_UMCType As String = "D_UMCType"
    Public D_ItemType As String = "D_ItemType"
    Public D_TransectionType As String = "D_TransectionType"
    Public D_PaymentType As String = "D_PaymentType"
    Public D_Month As String = "D_Month"
    Public D_Year As String = "D_Year"
    Public Item As String = "Item"
    Public ItemMovement As String = "ItemMovement"
    Public P_User As String = "P_User"
    Public Purchase As String = "Purchase"
    Public Purchase_Entry As String = "Purchase_Entry"
    Public Purchase_Payment As String = "Purchase_Payment"
    Public Sale As String = "Sale"
    Public Sale_Entry As String = "Sale_Entry"
    Public Sales_Batch As String = "Sales_Batch"
    Public Voucher As String = "Voucher"
    Public Voucher_Entry As String = "Voucher_Entry"
    Public Cheque As String = "Cheque"
    'Public Employee As String = "Employee"
    Public Item_View As String = "Item_View"
    Public ItemClass As String = "ItemClass"
    Public ItemClassComponent As String = "ItemClassComponent"
    Public Item_Class_View As String = "Item_Class_View"
    Public V_Promotion As String = "V_Promotion"
    Public Membership As String = "Membership"
    Public Reward As String = "Reward"
    Public Const ScriptExecute As String = "ScriptExecute"

End Module
